### ISSUE TITLE
Ignoring changes when calling changeState!

### ISSUE THREAD

**Issue by malx122** [PuppetJs/PuppetJs#85] opened 2016-04-26 07:20 UTC
We have a "command" client custom element that takes a couple of different  commands from the server and acts on the client.
One of the command is `morph_url` that tells the client to call `puppet.network.changeState` to a provided url.

However, the custom element also resets the command parameter to `''` in order to be able to receive the exactly same command again. But that change is never sent to server causing the servers and clients data model to differ!

Pseudo code in custom element, `command` is bounded to the"`Model.Command$`

```
commandChanged: function () {
   parsecommand();
   this.set('command', '');
   window.tu.puppetDirtyCheck(); (Utilityfunction to force the puppet  check that otherwise only reacts on click)
   ....
  ....
   puppet.network.changeState(parameterfromcommand);
          
}

```

**Comment by miyconst** [comment] 2016-04-26 08:13
Do you have `notify: true` in the `command` property declaration?

**Comment by malx122** [comment] 2016-04-26 08:14
Yes! As I said, the client model is updated. Its just not sent to server.

**Comment by miyconst** [comment] 2016-04-26 08:18
Am I right, that the change is not being sent to the server even with the next patches from the client side?

**Comment by malx122** [comment] 2016-04-26 08:58
Yepp, thats right. The client and server model differs even after a couple of patches.

**Comment by miyconst** [comment] 2016-04-26 09:08
That's definitely an error then.

@malx122 if you could create a small example which demonstration of the issue, it would be very useful.
@warpech take a look please.

**Comment by malx122** [comment] 2016-04-26 09:17
I think the first post describing the problem good enough. If you have trouble to repeat it locally, call me and I will show it.

**Comment by warpech** [comment] 2016-04-26 12:05
Does it work when you click on the page background or trigger window `mouseup` event as described here? https://github.com/PuppetJs/PuppetJs#generating-patches-based-on-local-changes

**Comment by warpech** [comment] 2016-04-26 12:05
Aha, I guess this is what `window.tu.puppetDirtyCheck();` does.

**Comment by warpech** [comment] 2016-04-26 12:06
Can you reproduce it in a small app, like https://github.com/warpech/SimplePuppet or https://github.com/StarcounterSamples/KitchenSink?

**Comment by malx122** [comment] 2016-04-29 14:04
Not sure, Ivar found out that it works if he wraps the set command in an async:
(which of course should not be needed)
```
this.async( function() {
     this.set('command', '');
     window.tu.puppetDirtyCheck();
 }).bind(this);
```

**Comment by malx122** [comment] 2016-05-25 14:07
The whole problem is that you "unobserve" the model while applying data patches from server. That is not ok since applying data patches may trigger javascript methods that makes other model changes themself. 

This problem has grown alot since this issue was created. We now have many sections of our code dependent on this working. And the workaround no longer works (not sure it ever worked for more than some lucky timing moments).

**Comment by warpech** [comment] 2016-05-25 14:38
@tomalec Question to you as the OT master... Do you think it is possible to apply remote patches without calling `unobserve` ... `observe`?

**Comment by tomalec** [comment] 2016-05-25 15:34
But we do not want those patches to trigger sending them back to server, do we?
So in some meaning we want unobserving it while applying.

Regarding

> The whole problem is that you "unobserve" the model while applying data patches from server. That is not ok since applying data patches may trigger javascript methods that makes other model changes themself.

OT could handle changes applied in-between applications of consecutive patches. 
So that's more a problem of JSON observer than JSON Patch OT.

As after application of incoming patch (possible synchronous changes), once we `unobserve`, we would need to compare whether something new (and different from incoming patch) was introduced.

**Comment by warpech** [comment] 2016-05-26 14:12
Discussed with @tomalec: Solution seems to be to reintroduce  object a mirror object in `puppet-polymer-client` that is not known to PuppetJs.

**Comment by warpech** [comment] 2016-06-01 08:11
Today I got a new idea :bulb: that might work *with* https://github.com/PuppetJs/puppet-polymer-client/issues/9

`puppet-polymer-client` does not have a mirror of `puppet.obj`. Instead, it is enough if it stops using `this.set` to apply the patches. Instead, it should:

- use regular `jsonpatch.apply` to apply the patches. This happens between `unobserve` and `observe`)
- use Polymer's `notifyPath` to announce the patches to Polymer. This happens in PuppetJs `onRemoteChange`. I think that this callback (and `onLocalChange`) should be moved after `observe()` to avoid side effects like described in the OT

Polymer's `notifyPath` is already used by us to notify `template is="dom-bind"`s in nested partials, so this should work OK.

**Comment by tomalec** [comment] 2016-06-01 08:20
I'd like to remid you that we did so in previous version of `puppet-polymer-client` ;) and we decided to switch not to fight with Polymer, but use it's public and more stable API.

**Comment by warpech** [comment] 2016-06-01 08:40
Not exactly the same. `puppet-polymer-client` was using its own `jsonpatch.apply` based on Polymer's `set` since [the second commit in this repo](https://github.com/PuppetJs/puppet-polymer-client/blob/090b5059ece4177e4f4be69b7c382a173bf808e0/puppet-polymer-client.html#L361)

So right now we are still fighting with Polymer in every `template is="dom-bind"` other than the root one. With the proposed change, we will use the same principle for the root template that is used for every other partial template.

**Comment by tomalec** [comment] 2016-06-02 10:45
Sorry, my bad it was [dom-bind-notifier](https://github.com/Juicy/dom-bind-notifier)

> So right now we are still fighting with Polymer in every template is="dom-bind" other than the root one. With the proposed change, we will use the same principle for the root template that is used for every other partial template.

Fair point

**Comment by joozek78** [comment] 2016-06-03 19:09
@tomalec @warpech Our current approach is to:

1. modify json-patch to return removed elements on application
 1. and puppet to propagate this info in callbacks
1. let puppet use json-patch to apply the patches
1. notify polymer afterwards
 1. polymer requires us to provide it with removed original elements when notifying about changes in arrays. This is reason for p1
1. should any client update the model in callback, those changes can be safely fed back to puppet

But it turns out that between puppet and json-patch sits a queue which can defer patch application - it's not guaranteed that patches are applied when they are sent to this queue. This makes p. 1a more complicated

**Comment by tomalec** [comment] 2016-06-05 09:33
I don't think queue will complicate a thing. You will simply trigger the
event once it's eventually applied.
3 cze 2016 21:09 "Marcin Goliński" <notifications@github.com> napisał(a):

**Comment by joozek78** [comment] 2016-06-22 10:54
This should be fixed now in new release

**Closed by joozek78** 2016-06-22 10:54 UTC
Labels: P/High
