### ISSUE TITLE
Websocket direct upgrade.

### ISSUE THREAD

**Issue by andwah** [PuppetJs/PuppetJs#59] opened 2015-06-10 09:07 UTC
When using websockets the connection is not upgraded until the first request is made from the client.

It would be nice if the connection is **directly** upgraded so the server can begin pushing data to client.

**Comment by warpech** [comment] 2015-06-10 12:45
This is a bug, since the code actually calls `webSocketUpgrade` in network `establish`.

@miyconst could you take a look?

The case is that you have pages like dashboards, chatrooms, etc, that should be available for WebSocket server push immediately after page load.

**Comment by andwah** [comment] 2015-06-10 13:06
I just retested this and now it seems to work (strange)... i will try to make a deeper test.

**Comment by tomalec** [comment] 2015-06-10 16:05
That is true that, Puppet opens WebSocket after first HTTP request, but this request should be made on page load. It seems to be another reason to restructure the way we obtain URL for WebSocket connection.

**Comment by miyconst** [comment] 2015-06-12 13:23
@andwah is this still reproducible? Give me the steps to reproduce if so, please.

**Comment by miyconst** [comment] 2015-06-12 13:27
Chatter app works immediately after load.

**Comment by miyconst** [comment] 2015-06-15 18:48
Ping @andwah.

**Comment by andwah** [comment] 2015-06-15 21:22
@miyconst I could not reproduce it.

**Comment by miyconst** [comment] 2015-06-16 06:47
@andwah thank you for testing. I close the issue as it is assigned to me.

**Closed by miyconst** 2015-06-16 06:47 UTC
Labels: bug
